boot.o: boot.S multiboot.h x86_desc.h types.h
idt_wrapper.o: idt_wrapper.S
isr_wrapper.o: isr_wrapper.S
x86_desc.o: x86_desc.S x86_desc.h types.h
filesys.o: filesys.c filesys.h types.h lib.h keyboard.h rtc.h i8259.h
i8259.o: i8259.c i8259.h types.h lib.h keyboard.h filesys.h
interrupt_handler.o: interrupt_handler.c lib.h types.h keyboard.h \
  filesys.h i8259.h rtc.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h keyboard.h \
  filesys.h i8259.h debug.h tests.h _idt.h paging.h rtc.h syscall.h
keyboard.o: keyboard.c keyboard.h types.h lib.h filesys.h i8259.h
lib.o: lib.c lib.h types.h keyboard.h filesys.h
paging.o: paging.c paging.h types.h
process.o: process.c process.h types.h filesys.h
_rtc.o: _rtc.c rtc.h lib.h types.h keyboard.h filesys.h i8259.h
syscall.o: syscall.c syscall.h types.h filesys.h paging.h process.h lib.h \
  keyboard.h x86_desc.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h keyboard.h filesys.h
